import = ["~/dotfiles/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.92
blur = true
padding = { x = 24, y = 24 }
decorations = "Buttonless"

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 18

[cursor]
style = { blinking = "On", shape = "Beam" }
vi_mode_style = { blinking = "On", shape = "Block" }
