. ~/.zsh/aliases.zsh
. ~/.zsh/bindings.zsh
. ~/.zsh/config.zsh
. ~/.zsh/colors.zsh
. ~/.zsh/completions.zsh
. ~/.zsh/fasd.zsh
. ~/.zsh/history.zsh
. ~/.zsh/java.zsh
. ~/.zsh/prompt.zsh
. ~/.zsh/rbenv.zsh
. ~/.zsh/vimify.zsh
