. ~/.zsh/aliases.zsh
. ~/.zsh/bindings.zsh
. ~/.zsh/config.zsh
. ~/.zsh/colors.zsh
. ~/.zsh/completions.zsh
. ~/.zsh/fasd.zsh
. ~/.zsh/fzf.zsh
. ~/.zsh/heroku.zsh
. ~/.zsh/history.zsh
. ~/.zsh/golang.zsh
. ~/.zsh/java.zsh
. ~/.zsh/prompt.zsh
. ~/.zsh/rbenv.zsh
. ~/.zsh/nvm.zsh
. ~/.zsh/vimify.zsh
. ~/.zsh/yarn.zsh
